server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging.file.name: logs/@project.artifactId@.log

management:
  endpoints.web:
    exposure.include: health, info, logfile, metrics, prometheus
    cors:
      allowed-origins: "*"
      allowed-methods: GET
  endpoint.health.show-details: always

spring:
  application.name: fuego-quasar-api
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create


  h2.console.enabled: true